version: 2.1

defaults: &defaults
  docker:
    - image: wunderio/circleci-codeception-base
    - image: circleci/mariadb:10.2
      environment:
        MYSQL_DATABASE: drupal
        MYSQL_ROOT_PASSWORD: badpassword
        MYSQL_ROOT_HOST: "%"
    - image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
      environment:
        - discovery.type=single-node
        - http.host=0.0.0.0
        - transport.host=127.0.0.1
        - xpack.security.enabled=false
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

jobs:
  build:
    docker:
      - image: wunderio/circleci-codeception-base

    steps:
      - run:
          name: Create Drupal
          command: |
            composer create-project drupal/recommended-project drupal
            cd drupal
            composer require drush/drush:9
      - save_cache:
          paths:
            - ~/project/drupal
          key: v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}

  test:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project/drupal/web/modules/elasticsearch_helper
      - restore_cache:
          keys:
            - v2-composer-dependencies-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Dependencies
          command: |
            cd drupal && COMPOSER_MEMORY_LIMIT=-1 composer install -n --prefer-dist --ignore-platform-reqs
      - run:
          name: Install Drupal
          command: |
            cd drupal && drush si --db-url=mysql://root:badpassword@127.0.0.1:3306/drupal --account-pass=admin -y
      - run:
          name: Install Elasticsearch Helper
          command: |
            cd drupal && drush pm-enable elasticsearch_helper

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build